# Generated by Django 2.2.4 on 2019-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190818_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-com_published',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
